[metadata]
  name = "graphsync"
  author = "Adin Schmahmann"

[global]
  plan = "data-transfer"
  case = "graphsync"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"
  disable_metrics = false

[[groups]]
  id = "group1"
  [groups.instances]
    count = 2
  [groups.run]
    [groups.run.test_params]
      latency = "100ms"
      bandwidth = "10MiB"
      transports = "tcp"
      muxers = "mplex"
      security = "tls"
      dagtype="deep-ipld"
      dagparams="{\"Padding\" : \"128 KiB\", \"Depth\" : 200}"
      bslatency="100ms"
