[metadata]
  name = "tcp"
  author = "Adin Schmahmann"

[global]
  plan = "data-transfer"
  case = "tcp"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"
  disable_metrics = false

[[groups]]
  id = "group1"
  [groups.instances]
    count = 2
  [groups.run]
    [groups.run.test_params]
      latency = "10ms"
      bandwidth = "100GiB"
      dagtype="unixfs-file"
      dagparams="1 GB"
      #dagtype="deep-ipld"
      #dagparams="10"
