[metadata]
  name = "bitswap"
  author = "Adin Schmahmann"

[global]
  plan = "data-transfer"
  case = "bitswap"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"
  disable_metrics = false

[[groups]]
  id = "group1"
  [groups.instances]
    count = 2
  [groups.run]
    [groups.run.test_params]
      latency = "500ms"
      bandwidth = "1GiB"
      transports = "tcp"
      muxers = "yamux"
      security = "tls"
